<#
.SYNOPSIS
    Processes the ArchiveQueue.json generated by the Dashboard and archives SharePoint sites.
.DESCRIPTION
    Reads Logs\ArchiveQueue.json, archives each queued site using Set-SPOSite -ArchiveStatus Archived,
    and updates the status in the queue file. After processing, refreshes site info via Get-SPOSite.
.PARAMETER AdminUrl
    SharePoint Admin URL (e.g., https://contoso-admin.sharepoint.com)
.PARAMETER QueueFile
    Path to ArchiveQueue.json (default: Logs\ArchiveQueue.json)
.PARAMETER Unattended
    Skip confirmation prompts
.EXAMPLE
    .\Start-ArchiveWebsites.ps1 -AdminUrl https://contoso-admin.sharepoint.com
.EXAMPLE
    .\Start-ArchiveWebsites.ps1 -AdminUrl https://contoso-admin.sharepoint.com -Unattended
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string]$AdminUrl,
    
    [string]$QueueFile,
    
    [switch]$Unattended
)

$ErrorActionPreference = "Stop"
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path

# Default queue file path
if (-not $QueueFile) {
    $QueueFile = Join-Path $scriptRoot "Logs\ArchiveQueue.json"
}

Write-Host ""
Write-Host "========================================================" -ForegroundColor Cyan
Write-Host "  SHAREPOINT SITE ARCHIVER" -ForegroundColor Cyan
Write-Host "========================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "  Admin URL: $AdminUrl" -ForegroundColor Gray
Write-Host "  Queue File: $QueueFile" -ForegroundColor Gray
Write-Host ""

# Check queue file
if (-not (Test-Path $QueueFile)) {
    Write-Host "  [ERROR] Queue file not found: $QueueFile" -ForegroundColor Red
    Write-Host "  Use the Dashboard Archive tab to select sites and generate ArchiveQueue.json" -ForegroundColor Yellow
    exit 1
}

# Load queue
$queue = Get-Content $QueueFile -Raw | ConvertFrom-Json
$queuedSites = @($queue.Sites | Where-Object { $_.Status -eq "Queued" })

if ($queuedSites.Count -eq 0) {
    Write-Host "  [OK] No queued sites to archive." -ForegroundColor Green
    exit 0
}

Write-Host "  Sites to archive: $($queuedSites.Count)" -ForegroundColor Yellow
Write-Host ""

# Show list
$i = 0
foreach ($site in $queuedSites) {
    $i++
    $storageMB = if ($site.StorageUsedMB) { "$([math]::Round($site.StorageUsedMB, 0)) MB" } else { "--" }
    Write-Host "  $i. $($site.Title) ($storageMB)" -ForegroundColor White
    Write-Host "     $($site.SiteUrl)" -ForegroundColor Gray
}

Write-Host ""

# Confirm
if (-not $Unattended) {
    $confirm = Read-Host "  Proceed with archiving $($queuedSites.Count) sites? (Y/N)"
    if ($confirm -ne "Y" -and $confirm -ne "y") {
        Write-Host "  Cancelled." -ForegroundColor Yellow
        exit 0
    }
    Write-Host ""
}

# Connect to SPO
Write-Host "  Connecting to SharePoint Online..." -ForegroundColor Cyan

# Try app auth from AppPaths.json
$appPathsFile = Join-Path $scriptRoot "Logs\AppPaths.json"
$connected = $false

if (Test-Path $appPathsFile) {
    try {
        $appPaths = Get-Content $appPathsFile -Raw | ConvertFrom-Json
        if ($appPaths.EntraIdApp -and $appPaths.EntraIdApp.ClientId -and $appPaths.EntraIdApp.CertificateThumbprint -and $appPaths.EntraIdApp.TenantId) {
            $tenantDomain = ($AdminUrl -replace "https://", "" -replace "-admin\.sharepoint\.com.*", "") + ".onmicrosoft.com"
            Connect-SPOService -Url $AdminUrl -ClientId $appPaths.EntraIdApp.ClientId -CertificateThumbprint $appPaths.EntraIdApp.CertificateThumbprint -Tenant $tenantDomain -ErrorAction Stop
            Write-Host "  [OK] Connected via app auth" -ForegroundColor Green
            $connected = $true
        }
    }
    catch {
        Write-Warning "  App auth failed: $_. Trying interactive..."
    }
}

if (-not $connected) {
    Connect-SPOService -Url $AdminUrl -ErrorAction Stop
    Write-Host "  [OK] Connected interactively" -ForegroundColor Green
}

Write-Host ""

# Process sites
$successCount = 0
$failCount = 0
$siteIndex = 0

foreach ($site in $queue.Sites) {
    if ($site.Status -ne "Queued") { continue }
    $siteIndex++
    
    Write-Host "  [$siteIndex/$($queuedSites.Count)] Archiving: $($site.SiteUrl)" -ForegroundColor Yellow
    
    try {
        # Archive the site
        Set-SPOSiteArchiveState -Identity $site.SiteUrl -ArchiveState Archived -ErrorAction Stop
        
        $site.Status = "Archived"
        $site.ArchivedAt = (Get-Date).ToString("o")
        $site.Error = $null
        
        Write-Host "    [OK] Archived successfully" -ForegroundColor Green
        $successCount++
        
        # Verify status
        try {
            $spoSite = Get-SPOSite -Identity $site.SiteUrl -ErrorAction SilentlyContinue
            if ($spoSite) {
                $site.ArchiveStatus = $spoSite.ArchiveStatus
                $site.LockState = $spoSite.LockState
                Write-Host "    Verified: ArchiveStatus=$($spoSite.ArchiveStatus), LockState=$($spoSite.LockState)" -ForegroundColor Gray
            }
        }
        catch {
            Write-Host "    Could not verify status: $_" -ForegroundColor DarkGray
        }
    }
    catch {
        $site.Status = "Failed"
        $site.Error = $_.Exception.Message
        Write-Host "    [FAIL] $($_.Exception.Message)" -ForegroundColor Red
        $failCount++
    }
    
    # Save progress after each site
    $queue.LastUpdated = (Get-Date).ToString("o")
    $queue | ConvertTo-Json -Depth 10 | Set-Content -Path $QueueFile -Encoding UTF8 -Force
}

Write-Host ""
Write-Host "========================================================" -ForegroundColor Cyan
Write-Host "  ARCHIVE COMPLETE" -ForegroundColor Cyan
Write-Host "========================================================" -ForegroundColor Cyan
Write-Host "  Archived: $successCount" -ForegroundColor Green
if ($failCount -gt 0) {
    Write-Host "  Failed: $failCount" -ForegroundColor Red
}
Write-Host "  Queue file updated: $QueueFile" -ForegroundColor Gray
Write-Host ""
